apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base-deployment
  name: base-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: base-deployment
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
status: {}
