apiVersion: v1
kind: Service
metadata:
  name: base-deployment-svc
  labels:
    app: base-deployment
spec:
  ports:
    - port: 80
      target: 80
  selector:
    app: base-deployment
  type: ClusterIP
