apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-name
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: new-name
          image: nginx:latest
          resources:
            limits:
              cpu: 100Mi
              memory: 100M
