apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-a

namePrefix: dev-

patches:
  - path: ./deployment-patch.yml
    target:
      kind: Deployment
    options:
      allowNameChange: true
resources:
  - ../../base
